context:
  name: acts
  version: "41.1.0"

recipe:
  name: ${{ name }}-suite
  version: ${{ version }}

source:
  url: https://github.com/acts-project/acts/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2cd559003d7c37c089adef0c357b7cb8dee7d2fa55f26d83ac41b3e9a2a1c22c
  # git: https://github.com/acts-project/acts.git
  # tag: v${{ version }}
  # lfs: true

outputs:
  - package:
      name: ${{ name|lower }}-core

    build:
      script:
        - if: unix
          then:
            - cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${PREFIX} -S . -B build
            - cmake -LH build
            - cmake --build build --parallel=${CPU_COUNT}
        - if: win
          then:
            - cmake %CMAKE_ARGS% -S . -B build
            - cmake -LH build
            - cmake --build build --parallel=%CPU_COUNT%
        - cmake --install build
      number: 0
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - make
      host:
        - libboost-devel
        - eigen
    tests:
      - script:
        - echo "Completed build"

about:
  homepage: https://acts.readthedocs.io/
  summary: 'ACTS is an experiment-independent toolkit for (charged) particle track reconstruction in (high energy) physics experiments implemented in modern C++.'
  description: |
    The ACTS project provides high-level track reconstruction modules that can be used for any tracking detector. The tracking detector geometry description is optimized for efficient navigation and fast extrapolation of tracks. Converters for several common geometry description packages are available. In addition to the algorithmic code, this project also provides an event data model for the description of track parameters and measurements.
  license: MPL-2.0
  license_file: LICENSE
  documentation: https://acts.readthedocs.io/
  repository: https://github.com/acts-project/acts

extra:
  feedstock-name: acts
  recipe-maintainers:
    - Snakemonster
    - matthewfeickert
